# Generated by Django 5.1.5 on 2025-02-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_student',
            name='phone',
            field=models.CharField(default='noData', max_length=60),
            preserve_default=False,
        ),
    ]
