# Generated by Django 5.1.5 on 2025-02-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_all_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_student',
            old_name='phone',
            new_name='city',
        ),
    ]
