# Generated by Django 5.1.5 on 2025-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Nothing', max_length=100),
            preserve_default=False,
        ),
    ]
