# Generated by Django 5.1.5 on 2025-02-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
        migrations.DeleteModel(
            name='homeapp',
        ),
    ]
